### ISSUE TITLE
thanks for this amazing code!

### ISSUE THREAD

**Issue by JaeDukSeo** [alexhamiltonRN/ProstateX#1]
thanks for this amazing code!

**Comment by alexhamiltonRN** [comment]
@JaeDukSeo - thanks for the kind comment!

**Comment by JaeDukSeo** [comment]
@alexhamiltonRN welcome! Thanks for the code.

Just a question, as a CS person who is not that familiar with MRI data, I was just wondering if you can share some sources where you learned how to deal with different MRI data. 

I am looking at your resampling nifi code and not really quite getting methods such as setSpacing and setDirection. 

Please and thank you! :D

**Comment by alexhamiltonRN** [comment]
Hi @JaeDukSeo -- This SimpleITK tutorial made it much clearer for me - hope it helps! http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/03_Image_Details.html

**Comment by JaeDukSeo** [comment]
thank you!

**Comment by alexhamiltonRN** [comment]
@JaeDukSeo - I just found another link and application that you might find helpful for understanding medical imaging coordinate systems. I think this one might help a little more!

https://www.slicer.org/wiki/Coordinate_systems

**Comment by JaeDukSeo** [comment]
Whoop Whoop thank you! Have  a nice day
